
# Site settings
title: Artificial Intelligence and Statistics Conference
description: > # this means to ignore newlines until "baseurl:"
  This is the website of the AISTATS conference.
baseurl: "/aistats1985" # the subpath of your site, e.g. /blog/
url: "http://www.aistats.org" # the base hostname & protocol for your site
#twitter_username: aistat
github_username:  aistats
author:
  name: AISTATS
  email:
comments: false
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: aistats

ghub:
  edit: true
  repository: aistats1985

banner: 

# Build settings
markdown: kramdown

conference:
  draft: false # set to True if the programme is draft only.
  image: 
  hide_tentative: true
  proceedings:
    url: https://books.google.com/books/about/Artificial_Intelligence_and_Statistics.html?id=CVRQAAAAMAAJ
    show: true
  room: 
  venue:  
  venue_url: 
  location: 
  full_name: Artificial Intelligence and Statistics
  short_name: AISTATS
  name: Artificial Intelligence and Statistics
  year: 1985
  instance: 
  styling: Workshop on
  dates:
  - 1985-04-01
  chairs:
  - type: Chair
    people:
    - family: Gale
      given: William A.
      institute: AT&T Bell Laboratories
      url: 
# change encoding for the generated output files to utf-8
encoding: utf-8


